# Generated by Django 3.0.7 on 2021-04-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='st_model',
            new_name='happySquirrel',
        ),
    ]
