# Generated by Django 3.0.7 on 2021-04-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20210415_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happysquirrel',
            name='date',
            field=models.CharField(help_text='Format: YYYY-MM-DD', max_length=10),
        ),
    ]
